openapi: 3.0.0
info:
  version: 0.1.0
  title: BCC Server API
  description: API for BCC Site and Dashboard
servers:
  - url: /api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
  parameters: {}
paths:
  /auth/signin:
    post:
      summary: Email-Pass SignIn
      description: Email-Pass SignIn, successfull respond with user data and token data.
      security: []
      tags:
        - Authentication
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
              required:
                - email
                - password
      responses:
        "200":
          description: Object with user data and token data.
  /auth/signup:
    post:
      summary: Email-Pass SignUp
      description: Email-Pass SignUp, successfull respond with user data and token
        data to authenticate on the go.
      security: []
      tags:
        - Authentication
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
                username:
                  type: string
                  minLength: 3
                displayName:
                  type: string
                  minLength: 3
              required:
                - email
                - password
                - username
              description: Email-Pass Signup payload Schema
      responses:
        "200":
          description: Object with user data and token data.
